# bash_profile

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

##
# Your previous /Users/rdown/.bash_profile file was backed up as /Users/rdown/.bash_profile.macports-saved_2013-12-12_at_04:34:47
##

# MacPorts Installer addition on 2013-12-12_at_04:34:47: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

